# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-22 17:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('userManager', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date_to',
            field=models.DateField(),
        ),
    ]
