# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-26 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0002_auto_20160726_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripsjoined',
            name='joined_by',
        ),
        migrations.RemoveField(
            model_name='tripsjoined',
            name='trip',
        ),
        migrations.AlterField(
            model_name='trip',
            name='joined_by',
            field=models.ManyToManyField(related_name='User2', to='trips.User'),
        ),
        migrations.DeleteModel(
            name='TripsJoined',
        ),
    ]
